# Generated by Django 4.2.5 on 2023-09-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='search',
            field=models.TextField(default='ggja'),
            preserve_default=False,
        ),
    ]
