# Generated by Django 4.2.5 on 2023-09-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='search',
        ),
    ]
